// APP
export const DISPLAY_PLAYER = "DISPLAY_PLAYER";

// LOADING
export const SET_ACTION_LOADING_STATE = "SET_ACTION_LOADING_STATE";

// PLAYER
export const LOAD_PLAYER = "LOAD_PLAYER";
export const STOP_AUDIO = "STOP_AUDIO";
export const SET_PLAYER_PLAYING = "SET_PLAYER_PLAYING";
export const SET_PLAYER_PAUSED = "SET_PLAYER_PAUSED";
export const UPDATE_PLAYER_TIMES = "UPDATE_PLAYER_TIMES";
export const SET_PLAYER_CURRENT_TIME = "SET_PLAYER_CURRENT_TIME";
export const DECREASE_PLAYER_VOLUME = "DECREASE_PLAYER_VOLUME";
export const INCREASE_PLAYER_VOLUME = "INCREASE_PLAYER_VOLUME";
export const LOAD_NEXT_TRACK = "LOAD_NEXT_TRACK";
export const LOAD_PREVIOUS_TRACK = "LOAD_PREVIOUS_TRACK";

// TRACK
export const FETCH_TRACKS = "FETCH_TRACKS";
