// APP
export const DISPLAY_PLAYER = "DISPLAY_PLAYER";

// LOADING
export const SET_ACTION_LOADING_STATE = "SET_ACTION_LOADING_STATE";

// PLAYER
export const LOAD_PLAYER = "LOAD_PLAYER";
export const RESET_PLAYER = "RESET_PLAYER";
export const SET_PLAYER_PLAYING = "SET_PLAYER_PLAYING";
export const SET_PLAYER_PAUSED = "SET_PLAYER_PAUSED";
export const UPDATE_PLAYER_TIMES = "UPDATE_PLAYER_TIMES";
export const SET_PLAYER_CURRENT_TIME = "SET_PLAYER_CURRENT_TIME";

// TRACK
export const FETCH_TRACKS = "FETCH_TRACKS";
