// APP
export const SET_SHOW_PLAYER = "SET_SHOW_PLAYER";

// LOADING
export const SET_ACTION_STATE = "SET_ACTION_STATE";

// PLAYER
export const SET_AUDIO = "SET_AUDIO";
export const SET_PLAYER_STATE = "SET_PLAYER_STATE";
export const SET_VOLUME = "SET_VOLUME";
export const SET_CURRENT_PROGRESS = "SET_CURRENT_PROGRESS";
export const SET_CURRENT_TIME = "SET_CURRENT_TIME";
export const SET_TRACK_DURATION = "SET_TRACK_DURATION";
export const SET_TITLE = "SET_TITLE";

// TRACKS
export const SET_TRACKS = "SET_TRACKS";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
