export const fakeApiResponse = {
  id: 47186198,
  kind: "track",
  created_at: "2012/05/22 11:23:27 +0000",
  last_modified: "2017/05/19 15:24:12 +0000",
  permalink: "cartoon-1-1-theory-wizardry",
  permalink_url:
    "https://soundcloud.com/cartoon-theory/cartoon-1-1-theory-wizardry",
  title:
    "Cartoon Theory - Planet Geisha - Wizardry Mind (Ft TRAVIS ORBIN & PLINI)",
  duration: 430668,
  sharing: "public",
  waveform_url: "https://wave.sndcdn.com/eGq9OOJJPWH0_m.png",
  stream_url: "https://api.soundcloud.com/tracks/47186198/stream",
  uri: "https://api.soundcloud.com/tracks/47186198",
  user_id: 2492274,
  artwork_url: "https://i1.sndcdn.com/artworks-000147293574-4r6s7h-large.jpg",
  comment_count: 76,
  commentable: true,
  description:
    "This is Wizardry Mind old track which will be on the album Planet Geisha. this Track is remix but not mastered for the moment. ",
  download_count: 138,
  downloadable: false,
  embeddable_by: "all",
  favoritings_count: 0,
  genre: "Progressive",
  isrc: "",
  label_id: null,
  label_name: "",
  license: "all-rights-reserved",
  original_content_size: 15401879,
  original_format: "mp3",
  playback_count: 0,
  purchase_title: null,
  purchase_url: null,
  release: "",
  release_day: null,
  release_month: null,
  release_year: null,
  reposts_count: 14,
  state: "finished",
  streamable: true,
  tag_list: "",
  track_type: "",
  user: {
    avatar_url: "https://i1.sndcdn.com/avatars-000148696935-85t8r1-large.jpg",
    id: 2492274,
    kind: "user",
    permalink_url: "http://soundcloud.com/cartoon-theory",
    uri: "https://api.soundcloud.com/users/2492274",
    username: "Cartoon Theory",
    permalink: "cartoon-theory",
    last_modified: "2017/12/21 06:59:47 +0000"
  },
  likes_count: 179,
  bpm: null,
  key_signature: "",
  user_favorite: false,
  user_playback_count: null,
  video_url: null,
  download_url: null
};

export const fakeTransformedData = {
  artworkUrl: "https://i1.sndcdn.com/artworks-000147293574-4r6s7h-t500x500.jpg",
  duration: 430668,
  id: 47186198,
  liked: false,
  likesCount: 179,
  permalinkUrl:
    "https://soundcloud.com/cartoon-theory/cartoon-1-1-theory-wizardry",
  playbackCount: 0,
  streamUrl:
    "https://api.soundcloud.com/tracks/47186198/stream?d02c42795f3bcac39f84eee0ae384b00",
  streamable: true,
  title:
    "Cartoon Theory - Planet Geisha - Wizardry Mind (Ft TRAVIS ORBIN & PLINI)",
  userId: 2492274,
  userPermalinkUrl: "http://soundcloud.com/cartoon-theory",
  username: "Cartoon Theory",
  waveformUrl: "https://wave.sndcdn.com/eGq9OOJJPWH0_m.json"
};
